<a href="https://colab.research.google.com/github/gnommer/pytorch/blob/main/0_Fundamentals_of_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Installation of Pytorch

pytorch can be install from the official pytorch website. various versions are available for various os options. here python will be used to download it to colab.

Link: https://pytorch.org/get-started/locally/

In [18]:
!pip3 install torch torchvision >> /dev/null

Doing a quick check to see if torch is installed properly and that the tensors can be intialize. if everything works fine then we would have a 5x3 tensor defined below.

In [5]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.2724, 0.4769, 0.1775],
        [0.1275, 0.2341, 0.5268],
        [0.0433, 0.5923, 0.1963],
        [0.6098, 0.0036, 0.1688],
        [0.0191, 0.4904, 0.4838]])



# Creating tensors
PyTorch loves tensors. So much so there's a whole documentation page dedicated to the [torch.Tensor](https://pytorch.org/docs/stable/tensors.html) class

here we will create a basic tensor. understand the attributes contained and functions that can be peformed on a tensor.

## Scaler

a tensor of dimension 0 is called a scaler and its just a simple number.

In [6]:
# create a scaler using torch
scaler = torch.tensor(7)
scaler

tensor(7)

when we try see the dimensions using ```ndim``` attribute we can see that the scaler has a 0 dimension. no associated direction only magnitude.

In [15]:
scaler.ndim

0

here we can see that the ```item()``` function can be used to retrieve the original tensor numbers from memory.

In [8]:
scaler.item()

7

## Vector

A Vector is a single dimension tensor but can contain many numbers so lets say in the below cell we define a vector of dimension 1x2 meaning that there are 2 elements present in this vector. vectors are denoted with a single list as seen below.

In [10]:
vector = torch.tensor([5, 3])
vector

tensor([5, 3])

The ```ndim``` attribute is executed to check the dimension. we can see that only the first dimension of 1x2 vector is is denoted here. vectors can grow in size to how many elements they want. but how to know the actual size of a vector ?

In [16]:
vector.ndim

1

using ```shape``` atribute we can see that the number of elements inside a tensor are retrieved.

In [14]:
vector.shape

torch.Size([2])

## Matrix

when multiple vectors are encased in a list we get a matrix below is the representation of a matrix.

In [ ]:
matrix = torch.tensor([[10, 5],
                       [2, 1]])
matrix

the `ndim` attribute returns the dimension of the matix and its 2 indicating 2 vectors (aka tensors of ndim 1) are present in it.

In [19]:
matrix.ndim

2

the `shape` yields the actual size of the matix which is 2x2 here

In [20]:
matrix.shape

torch.Size([2, 2])

## Tensor

A tensor is nothing but a 3-d vector representing 3 different dimensions. its usually in the last dimension the information is stored.

In [22]:
tensor = torch.Tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

tensor

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

here `ndim` shows that there are 3 dimensions to our tensor. indicating its 3 levels deep

In [23]:
tensor.ndim

3

lets run the `shape` attribute and see what is the shape we get. the expectation is to get a 1x3x3 here. because we just encased a matrix inside another dimension here, so lets say you have some information to represent about 2 people and inform about them is 2x2 matrix then the tensor would be of shape 2x2x2. capturing the info of both.

In [24]:
tensor.shape

torch.Size([1, 3, 3])

Matrices and Tensors are usually denoted with Uppercase notation to indicate that its a complex structure of vectors or Matrices. this is usally seen this way M, A etc.

so now the basic blocks are understood lets understand why tensors are important in Machine Learning and Deep Learning

## Random Tensors
Every machine learning model stores the information in some form of a matrix and optimizes the random elements to essentially reach a learnable pattern of numbers. but how do we initialize these tensors. it is usally taken care by most packages but it lets understand the working of tensor class so lets work through it.


In [25]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.5114, 0.3874, 0.6947, 0.1406],
         [0.4624, 0.2801, 0.6025, 0.7394],
         [0.0539, 0.7044, 0.3743, 0.0539]]),
 torch.float32)

here we can see that a tensor of shape 3, 4 is created and each value is of float32 in dimension.

lets say we wanna represent an image as a tensor then this would be same as

In [28]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

here we can see a tensor of random values is initialized. here we can see the 224, 224 represent the actual image and 3 denotes the channel of a image. a image usually containes three representations of RGB. these channels combine to form a image.

## Zeros and ones

we would also need to understand the ability to create zeros and ones tensors here. this lets us define unit and zero tensors which can be used for further implementations.

In [29]:
zero_matrix = torch.zeros(size=(3,3))
zero_matrix, zero_matrix.shape

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 torch.Size([3, 3]))

here we can see a zero matrix is initialized. all the elements of the matrix are zeros. same can be done in higher dimensions.

In [30]:
ones_matrix = torch.ones(size=(3,3))
ones_matrix, ones_matrix.shape

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.Size([3, 3]))

here we can see that the unit matrix of 3x3 is created with this quick command.

knowing these two implementations will help us with tensor manipulations later.

## Range of Values

we can also create a range of values in pytorch similar to python function range

In [31]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Tensor Datatypes

we can create tensors of type float 16, 32, 64 some shorthands in pytorch for these are `pytorch.half` for 16 bit  and `pytorch.double` 64 bit. any tensor is created with 32 bits by default.

why would these datatypes matter. this depends on the nature of the problem where higher precision is required which intern required more bits. in astronomy double is used more often. but in normal business problems a 32 bit should suffice.

higher precsion datatype usually means better results. but the time to manipulate the tensors is longer. so choosing the right dtype for a problem is must.

In [32]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

# Getting Information from Tensors

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

- shape - what shape is the tensor? (some operations require specific shape rules)
- dtype - what datatype are the elements within the tensor stored in?
- device - what device is the tensor stored on? (usually GPU or CPU)
Let's create a random tensor and find out details about it.

In [34]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.1499, 0.5741, 0.2834, 0.0244],
        [0.4710, 0.6099, 0.7977, 0.4806],
        [0.9457, 0.9902, 0.1881, 0.9292]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Manipulating Tensors

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:

- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication
And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

## Basic Operations

In [35]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [36]:
tensor * 10

tensor([10, 20, 30])

In [37]:
tensor

tensor([1, 2, 3])

The tensor values are not changes unless reassigned.

In [39]:
tensor = tensor - 10
tensor = tensor + 10
tensor

tensor([1, 2, 3])

here we can see subtraction and addition has returned the original tensor. so we should reassign the tensor to retain the change.

In [40]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

we can also multiply two tensors. below is called element wise multiplication

In [57]:
tensor * tensor

tensor([1, 4, 9])

there is also matrix multiplication in tensors. its done using the symbol `@` below is an example to multiply a vector with matrix. the matrix is a a linear transform to stretch the vector by 2 times in both x and y dimensions. the resultant vector should be 2, 4 after matrix multiplication



In [43]:
vector = torch.tensor([1, 2])
matrix = torch.tensor([[2, 0],
                       [0, 2]])

print("using matrix @ vector: ", matrix @ vector)
print("using torch.matmul: ", torch.matmul(matrix, vector))

using matrix @ vector:  tensor([2, 4])
using torch.matmul:  tensor([2, 4])


as we can see both the vectors are same. `@` is handy but `torch.matmul` is more verbose and easy to read and understand.

In [44]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value


CPU times: user 794 µs, sys: 941 µs, total: 1.73 ms
Wall time: 1.71 ms


tensor(14)

In [46]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 121 µs, sys: 11 µs, total: 132 µs
Wall time: 136 µs


tensor(14)

also torch.matmul is more effecient and faster implementation than loop based computation. its a more effecient parallelized function. always use it if matrix multiplication is needed

Transpose if a operation to flip the tensor dimensions. this helps with certain linear algebra math like checking if vectors are othrogonal or if matices are idemponent. calling .T attribute will yield the transpose of the tensor

In [61]:
matrix = torch.tensor([[1 , 0],
                       [2,  1]])
matrix @ matrix.T

tensor([[1, 2],
        [2, 5]])

## Linear Tranformations (nn modules)

here we can see when we try to multiply the torch tensors with transpose for this square matrix the effect is that an diagonal matrix is returned. this is because the transpose flips the matrix of row 1 to column 1 in new matrix. when transporse if multiplied with it. we see the row2 has the y dimension increased. essentially [2, 1] is multiplied elementwise with [2, 1] in transpose to raise it to 5 in last matrix element

note: matrix shapes have to be compatable for the matrix multiplication operations to work. 2x3 can only be multiplied with a matrix of 3x(some dimension) the columns of first matrix should match the rows of the second matrix

In [71]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
x = torch.tensor([3, 2], dtype=torch.float32)
output = linear(x)
print("shape of input: ", x.shape)
print("print linear tensor", linear.weight, linear.bias)
print("output", output, output.shape)

shape of input:  torch.Size([2])
print linear tensor Parameter containing:
tensor([[ 0.5406,  0.5869],
        [-0.1657,  0.6496],
        [-0.1549,  0.1427],
        [-0.3443,  0.4153],
        [ 0.6233, -0.5188],
        [ 0.6146,  0.1323]], requires_grad=True) Parameter containing:
tensor([ 0.5224,  0.0958,  0.3410, -0.0998,  0.5451,  0.1045],
       requires_grad=True)
output tensor([ 3.3181,  0.8979,  0.1615, -0.3021,  1.3776,  2.2130],
       grad_fn=<AddBackward0>) torch.Size([6])


here the output tensor is of size 6 after taking 6 inputs and this random size. linear is a tensor which is of shape 2 x 6 and is randomly initialized. it will also have two attributes `weight` and `bias`. essentialiiy the linear tranform can be summed up to a equation

$y = Wa + b$.

where $W$ is the weight matrix and $b$ is the bias matrix. here the input is taken converted to 1 x 6 vector and a bias vector is added to it

## Stat operations

In [75]:
print("Tensor min: ", tensor.min())
print("Tensor max: ", tensor.max())
print("Tensor sum: ", tensor.sum())
print("Tensor mean: ", tensor.type(torch.float32).mean())

Tensor min:  tensor(1)
Tensor max:  tensor(3)
Tensor sum:  tensor(6)
Tensor mean:  tensor(2.)


these are some other normal stat functions which can be run on tensors. there are their equivalent functions like torch.min, max, sum, mean etc

In [76]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


this argmin, argmax operations can be used to identify the element with max or minimum value and return the index associated with it. this is useful when performing softmax operation of choosing the element with highest probability function.

## Reshapes, Stack, squeezing, unsqueezing

In [78]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

x_reshaped = x.reshape(1, 7)

z = x.view(1, 7)

z, z.shape, x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]),
 torch.Size([1, 7]),
 tensor([[1., 2., 3., 4., 5., 6., 7.]]),
 torch.Size([1, 7]))

here both `view` and `reshape` functions can be used to reshape a vector like here the size is reduced from 8 elements to 7 elements.

In [80]:
x[0] = 5
x_reshaped, z

(tensor([[5., 2., 3., 4., 5., 6., 7.]]),
 tensor([[5., 2., 3., 4., 5., 6., 7.]]))

here we can see `reshape` and `view` both just show the vector x in specified shape and can be changed accordingly.

In [81]:
torch.stack([x, x, x, x, x], dim=1)

tensor([[5., 5., 5., 5., 5.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.]])

here the vectors are stacked in column fashion this is similar to column stack in pandas. dim=1 means do the op in column fashion. dim=0 means do it in row fashion.

In [85]:
z.squeeze().shape

torch.Size([7])

here we can see that the vector is squeezed from 1x7 to 7 size single dim. unsqueeze is the opposite of this

In [88]:
z.unsqueeze(dim=0).shape

torch.Size([1, 1, 7])

In [89]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


here we can see that the vector is permuted from having 3 elements in each row to having 224 rows in last dimensions. this is useful when we are passing images to CNN model. the value in the permuted tensor will be the same as original tensor. only the view is changed.

# Tensors on GPU

In [2]:
import torch
torch.cuda.is_available()

True

here we can see that GPU is availble when using GPU runtime. its a simple callable to check if its available

In [3]:
torch.cuda.device_count()

1

In [9]:
tensor = torch.rand((5, 5))
gpu_tensor = tensor.to('cuda')
print("Tensor on cpu", tensor, tensor.device)
print("Tensor on gpu", gpu_tensor, gpu_tensor.device)

Tensor on cpu tensor([[0.1377, 0.0188, 0.8249, 0.7783, 0.0700],
        [0.1221, 0.5392, 0.6307, 0.6179, 0.6740],
        [0.4633, 0.0526, 0.6624, 0.4447, 0.9608],
        [0.1997, 0.3913, 0.8461, 0.6919, 0.5958],
        [0.6469, 0.8219, 0.1958, 0.1711, 0.8925]]) cpu
Tensor on gpu tensor([[0.1377, 0.0188, 0.8249, 0.7783, 0.0700],
        [0.1221, 0.5392, 0.6307, 0.6179, 0.6740],
        [0.4633, 0.0526, 0.6624, 0.4447, 0.9608],
        [0.1997, 0.3913, 0.8461, 0.6919, 0.5958],
        [0.6469, 0.8219, 0.1958, 0.1711, 0.8925]], device='cuda:0') cuda:0


here the tensor is moved to be handled in GPU using CUDA. we can see that to function returns a reference to the GPU tensor.to put the gpu tensor back on cpu its as simple as calling

In [10]:
cpu_tensor = gpu_tensor.cpu()
cpu_tensor.device

device(type='cpu')

In [15]:
torch.cuda.max_memory_allocated()
torch.cuda.empty_cache()
torch.cuda.max_memory_reserved()

2097152

In [16]:
!nvidia-smi

Thu Aug 31 10:19:08 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   77C    P0    31W /  70W |    601MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# Resources
- https://www.learnpytorch.io/00_pytorch_fundamentals/ - base article
- https://pytorch.org/docs/stable/tensors.html#torch-tensor - extended list of functions and details about torch.Tensor class
- https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics - cuda semantics for more details on how pytorch interacts with GPU and what else can be done.
